Repository kathteam/kath-v0.2-alpha, pull requests merged in 2025-05, with the labels that each got.

#25 VLE/GKBE-12/optimize_cadd
  app/back_end/src/routes/workspace_apply_route.py
  app/back_end/src/tools/cadd.py
Labels: enhancement, performance

#18 VLE/GKBE-9/spliceai_optimisation(CUDA)
  app/back_end/README.md
  app/back_end/requirements.txt
  app/back_end/src/routes/workspace_apply_route.py
  app/back_end/src/tools/spliceai.py
Labels: performance, refactor

#32 JTE/KFE-29/Editor_Go_To_Beginning
  app/front_end/src/features/editor/components/editorView/editorPaginationBarActions.tsx
  app/front_end/src/features/editor/components/editorView/editorView.tsx
  app/front_end/src/features/editor/components/editorView/index.ts
  app/front_end/src/features/editor/components/fileTreeView/fileTreeView.tsx
Labels: enhancement

#33 JTE/KFE-05/Apply_All_Button
  app/back_end/src/routes/workspace_apply_route.py
  app/front_end/src/features/editor/components/toolbarView/toolbarGroupButtons/applyGroupButtons.tsx
Labels: enhancement
